language: python
python:
  - "3.4"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - set -e
  - pytest
#  - flake8 # TODO: https://github.com/devopshq/teamcity/issues/3
